service:
  name: rpmed-service-api

plugins:
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-domain-manager

custom:
  serverless-offline:
    port: 4000
  dynamodb:
    stages:
      - dev
    start:
      migrate: true
      seed: true
      noStart: true
    seed:
      dev:
        sources:
          - table: ${self:service}-${opt:stage, self:provider.stage}-resources
            sources: [./seed/resources.json]
          - table: ${self:service}-${opt:stage, self:provider.stage}-users-lookup
            sources: [./seed/usersLookup.json]
  domain:
    dev: dev.rpmed-apps.com
    staging: staging.rpmed-apps.com
    prod: prod.rpmed-apps.com
  clientDomain:
    dev: dev-admin.medled.com
    staging: staging-admin.medled.com
    prod: admin.medled.com
  customDomain:
    domainName: ${self:custom.domain.${opt:stage, self:provider.stage}}
    basePath: ''
    stage: ${opt:stage, self:provider.stage}
    createRoute53Record: true

provider:
  name: aws
  runtime: nodejs8.10
  profile: rpmed-serverless
  region: us-west-2
  environment:
    ACCESS_TOKEN_LIFESPAN: 5m
    REFRESH_TOKEN_LIFESPAN: 7d
    SALT_ROUNDS: 10
    CLIENT_DOMAIN: ${self:custom.clientDomain.${opt:stage, self:provider.stage}}
    RECAPTCHA_KEY: 6LdOqZoUAAAAAJ79IuWa4mU57Urnd-N6oxP4XhiR
    OAUTH_SIGNATURE: 'Ph$2\@!Rq<ev_W;:N(2+>Bwxez$3?;9~srf*nxiVJLz:lw7Djgs(Q/UhwmZ@"YLi<'
    ATTACHED_IMAGES_BUCKET: ${self:service}-${opt:stage, self:provider.stage}-attached-images
    DYNAMODB_RESOURCES_TABLE: ${self:service}-${opt:stage, self:provider.stage}-resources
    DYNAMODB_RESOURCES_GSI_1: GSI_1
    DYNAMODB_RESOURCES_GSI_2: GSI_2
    DYNAMODB_USER_LOOKUP_TABLE: ${self:service}-${opt:stage, self:provider.stage}-users-lookup
    DYNAMODB_TOKEN_LOOKUP_TABLE: ${self:service}-${opt:stage, self:provider.stage}-tokens-lookup
    SES_SOURCE_ARN: arn:aws:ses:us-west-2:426380452104:identity/rpmed-apps.com

  iamRoleStatements:
    - Effect: Allow
      Action:
        - ses:SendEmail
      Resource: 'arn:aws:ses:us-west-2:426380452104:identity/rpmed-apps.com'
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
      Resource: 'arn:aws:s3:::${self:provider.environment.ATTACHED_IMAGES_BUCKET}/*'
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:BatchGetItem
      Resource: 'arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:service}-${opt:stage, self:provider.stage}-*'

functions:
  graphql:
    handler: app/apollo.graphqlHandler
    events:
      - http:
          path: graphql
          method: any
          cors: true
  token:
    handler: app/token.createToken
    events:
      - http:
          method: post
          path: auth/token
          cors: true
  forgotPassword:
    handler: app/forgot.sendResetPasswordEmail
    events:
      - http:
          method: post
          path: auth/forgot
          cors: true
  importSheets:
    handler: app/sheets.importSheets
    events:
      - http:
          method: get
          path: import/data
          cors: true
  modelsFromSheet:
    handler: app/sheets.importModels
    timeout: 60
  symptomsFromSheet:
    handler: app/sheets.importSymptoms
    timeout: 60
resources:
  # S3
  - ${file(resources/s3-bucket.yml)}
  # DynamoDB
  - ${file(resources/dynamo.yml)}
