# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:12.18.0

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: |
          npm config set "@fortawesome:registry" https://npm.fontawesome.com/ && \
          npm config set "//npm.fontawesome.com/:_authToken" $FONT_AWESOME_TOKEN

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      # - run: npm run test

  deploy:
    machine:
      enabled: true
    working_directory: ~/repo
    steps:
      - checkout
      - type: add-ssh-keys
      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
      - type: deploy
        name: 'Deploy to Heroku'
        command: |
          # Install Heroku fingerprint (this is heroku's own key, NOT any of your private or public keys)
          echo 'heroku.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAu8erSx6jh+8ztsfHwkNeFr/SZaSOcvoa8AyMpaerGIPZDB2TKNgNkMSYTLYGDK2ivsqXopo2W7dpQRBIVF80q9mNXy5tbt1WE04gbOBB26Wn2hF4bk3Tu+BNMFbvMjPbkVlC2hcFuQJdH4T2i/dtauyTpJbD/6ExHR9XYVhdhdMs0JsjP/Q5FNoWh2ff9YbZVpDQSTPvusUp4liLjPfa/i0t+2LpNCeWy8Y+V9gUlDWiyYwrfMVI0UwNCZZKHs1Unpc11/4HLitQRtvuk0Ot5qwwBxbmtvCDKZvj1aFBid71/mYdGRPYZMIxq1zgP1acePC1zfTG/lvuQ7d0Pe0kaw==' >> ~/.ssh/known_hosts

          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/rpmed-service-admin.git $CIRCLE_SHA1:refs/heads/master
          fi

          if [ "${CIRCLE_BRANCH}" == "staging" ]; then
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/rpmed-service-admin-staging.git $CIRCLE_SHA1:refs/heads/master
          fi

          if [ "${CIRCLE_BRANCH}" == "dev" ]; then
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/rpmed-service-admin-dev.git $CIRCLE_SHA1:refs/heads/master
          fi

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - develop
                - staging
