name: Audit

on:
  push:
    branches: 
      - develop
      - staging
      - master 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: npm audit action
      uses: oke-py/npm-audit-action@v1.0.1
      with:
        # GitHub access token used to create an issue
        token: ${{ secrets.GITHUB_TOKEN }}
        # Issue assignees (separated by commma)
        issue_assignees: jimjeffers
        # Issue assignees (separated by commma)
        issue_labels: security
