name: CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the master, staging, or dev branches
  push:
    branches:
      - master
      - staging 
      - dev

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: npm install
    - name: Serverless
      uses: serverless/github-action@v1.53.0
    - name: Deploying
      run: |
        serverless config credentials --provider aws --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY --profile rpmed-serverless

          if [ "${GITHUB_REF}" == "refs/heads/master" ]; then
            serverless deploy --stage prod --conceal
          fi

          if [ "${GITHUB_REF}" == "refs/heads/staging" ]; then
            serverless deploy --stage staging --conceal
          fi

          if [ "${GITHUB_REF}" == "refs/heads/develop" ]; then
            serverless deploy --stage dev --conceal
          fi
